version: '3'

networks:
  matrix_net:
    name: matrix_net

volumes:
  matrix_db:
    name: matrix_db
  matrix_turn:
    name: matrix_turn

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - matrix-server
    networks:
      - matrix_net
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  matrix-server:
    container_name: matrix-server
    image: docker.io/matrixdotorg/synapse:v1.92.2
    restart: unless-stopped
    depends_on:
      - matrix-db
    networks:
      - matrix_net
    ports:
      - 8008:8008/tcp
      - 8448:8448/tcp
    volumes:
      - ./synapse-data:/data
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml

  matrix-db:
    container_name: matrix-db
    image: docker.io/postgres:12-alpine
    restart: unless-stopped
    networks:
      - matrix_net
    volumes:
      - matrix_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=YOUR_POSTGRES_PWD_HERE
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      # ensures the database gets created correctly
      # https://matrix-org.github.io/synapse/latest/postgres.html#set-up-database
